apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/codefresh-io/cli-v2/manifests/argo-workflows

configMapGenerator:
- name: workflow-controller-configmap
  behavior: merge
  literals:
   - containerRuntimeExecutor=k8sapi
